DROP DATABASE IF EXISTS `MHGU`;

CREATE DATABASE `MHGU`;

USE `MHGU`;

CREATE TABLE `weapons` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    info VARCHAR(500)
);

CREATE TABLE `monsters` (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    deviant BOOLEAN NOT NULL,
    small_monster BOOLEAN NOT NULL,
    related_monsters VARCHAR(100),
    description text
);

INSERT INTO `weapons`(name, info) VALUES
    ('Great Sword', 'A mighty sword that makes up for its lack of mobility with huge, punishing attacks. The Great Sword can also block attacks, making it a good all-around weapon.'),
    ('Long Sword', 'A nimble weapon capable of extended combos. Charge up energy with each attack to use your powerful Spirit Blade attack'),
    ('Sword and Shield', 'A mobile weapon with fast recovery time between attacks. You can even use items or attack while blocking'),
    ('Dual Blades', 'A weapon that blitzes a target with a flurry of attacks. Activate Demon Mode, then continue the offensive to go into Archdemon Mode, which raises attack speed and power.'),
    ('Hammer', 'A blunt weapon used to smash monsters with powerful attacks. It can stun monsters with repeated blows to the head.'),
    ('Lance', 'A weapon coupled with a highly defensive shield. Lance users can block while moving and also counterattack. You can also charge forward with this weapon and perform a Jumping Attack, except in Strike Style.'),
    ('Gunlance', 'A Lance equipped with the ability to fire shells. Has high attack potential thanks to Wyverns Fire and Burst Fire, which uses all of your shells at once.'),
    ('Hunting Horn', 'Perform songs that boost your abilities and those of your friends. Weave your performances into your attacks to make the most of this weapons offensive and support capabilities.'),
    ('Switch Axe', 'Use the mobility and attack power of the Axe, and when you see a chance, switch to the powerful Sword. While in Sword Mode, aim to unleash a powerful Element Discharge.'),
    ('Charge Blade', 'A powerful weapon that morphs between a sword/shield combo and an axe. Accumulate energy with the nimble sword, and then switch to axe mode to unleash a thunderous, energy-filled attack.'),
    ('Insect Glaive', 'The Insect Glaive pairs a powerful glaive with Kinsects: insects that harvest extract from monsters to power you up. The Insect Glaive provides the hunter with great mobility and the ability to perform Jumping Attacks even on flat terrain.'),
    ('Light Bowgun', 'A long range projectile weapon. Utilizes a variety of ammo to do everything everything from rapidly shooting targets to providing support with status-changing ammo. Hit the target at critical range to maximize the weapons full potential. Critical range varies depending on the ammo.'),
    ('Heavy Bowgun', 'A powerful, long range projectile weapon. The heavy weight makes mobility a chore, but the firepower makes up for it. Use Crouching Fire to rapidly chain together shots. Hit the target at critical range to maximize damage Critical range varies depending on the ammo.'),
    ('Bow', 'The Bow is a versatile weapon thanks to its variety of Shots, including the long- ranged Arc Shot and the damaging Power Shot, and allows its user to be highly mobile as they fire off coated arrows as support. Hit the target at critical range to maximize the weapons full potential. Critical range varies depending on the type of arrow or arrow coating used.'),
    ('Prowler', 'Registering a Palico as a Prowler will let you control that Palico directly! Switch between modes via the Palico Board.');

INSERT INTO `monsters` (name, type, deviant, small_monster, related_monsters) VALUES
("Altaroth", "Neopteron", false, true, NULL),
("Anteka", "Herbivore", false, true, NULL),
("Apceros", "Herbivore", false, true, NULL),
("Aptonoth", "Herbivore", false, true, NULL),
("Blango", "Fanged Beast", false, true, "Blangonga"),
("Bnahabra", "Neopteron", false, true, NULL),
("Bullfango", "Fanged Beast", false, true, "Bulldrome"),
("Ceanataur", "Carapaceon", false, true, "Shogun Ceanataur, Rustrazor Ceanataur"),
("Cephalos", "Piscine Wyvern", false, true, "Cephadrome"),
("Conga", "Fanged Beast", false, true, "Congalala"),
("Felyne", "Lynian", false, true, "Melynx"),
("Gargwa", "Bird Wyvern", false, true, NULL),
("Genprey", "Bird Wyvern", false, true, "Gendrome"),
("Giaprey", "Bird Wyvern", false, true, "Giadrome"),
("Great Thunderbug", "Neopteron", false, true, NULL),
("Hermitaur", "Carapaceon", false, true, "Daimyo Hermitaur, Stonefist Hermitaur"),
("Hornetaur", "Neopteron", false, true, NULL),
("Ioprey", "Bird Wyvern", false, true, "Iodrome"),
("Jaggi", "Bird Wyvern", false, true, "Jaggia"),
("Jaggia", "Bird Wyvern", false, true, "Jaggi"),
("Kelbi", "Herbivore", false, true, NULL),
("Konchu", "Neopteron", false, true, NULL),
("Larinoth", "Herbivore", false, true, NULL),
("Ludroth", "Leviathan", false, true, "Royal Ludroth"),
("Maccao", "Bird Wyvern", false, true, "Great Maccao"),
("Melynx", "Lynian", false, true, "Felyne"),
("Moofah", "Herbivore", false, true, NULL),
("Mosswine", "Herbivore", false, true, NULL),
("Popo", "Herbivore", false, true, NULL),
("Remobra", "Snake Wyvern", false, true, NULL),
("Rhenoplos", "Herbivore", false, true, NULL),
("Slagtoth", "Herbivore", false, true, NULL),
("Uruktor", "Leviathan", false, true, "Agnaktor"),
("Velociprey", "Bird Wyvern", false, true, "Velocidrome"),
("Vespoid", "Neopteron", false, true, NULL),
("Zamite", "Amphibian", false, true, "Zamtrios"),
("Agnaktor", "Leviathan", false, false, "Uruktor"),
("Akantor", "Flying Wyvern", false, false, "Ukanlos"),
("Arzuros", "Fanged Beast", false, false, "Redhelm Arzuros"),
("Redhelm Arzuros", "Fanged Beast", true, false, "Arzuros"),
("Astalos", "Flying Wyvern", false, false, "Boltreaver Astalos"),
("Boltreaver Astalos", "Flying Wyvern", true, false, "Astalos"),
("Ahtal-Ka", "Neopteron", false, false, NULL),
("Barioth", "Flying Wyvern", false, false, NULL),
("Barroth", "Brute Wyvern", false, false, NULL),
("Basarios", "Flying Wyvern", false, false, "Gravios"),
("Blangonga", "Fanged Beast", false, false, NULL),
("Brachydios", "Brute Wyvern", false, false, "Raging Brachydios"),
("Raging Brachydios", "Brute Wyvern", false, false, "Brachydios"),
("Bulldrome", "Fanged Beast", false, false, "Bullfango"),
("Cephadrome", "Piscine Wyvern", false, false, "Cephalos"),
("Congalala", "Fanged Beast", false ,false, "Conga"),
("Daimyo Hermitaur", "Carapaceon", false, false, "Hermitaur, Stonefist Hermitaur"),
("Stonefist Hermitaur", "Carapaceon", true, false, "Hermitaur, Daimyo Hermitaur"),
("Deviljho", "Brute Wyvern", false, false, "Savage Deviljho"),
("Savage Deviljho", "Brute Wyvern", false, false, "Deviljho"),
("Diablos", "Flying Wyvern", false, false, "Bloodbath Diablos"),
("Bloodbath Diablos", "Flying Wyvern", true, false, "Diablos"),
("Duramboros", "Brute Wyvern", false, false, NULL),
("Gammoth", "Fanged Beast", false, false, "Elderfrost Gammoth"),
("Elderfrost Gammoth", "Fanged Beast", true, false, "Gammoth"),
("Gendrome", "Bird Wyvern", false, false, "Gendrome"),
("Giadrome", "Bird Wyvern", false, false, "Giaprey"),
("Glavenus", "Brute Wyvern", false, false, "Hellblade Glavenus"),
("Hellblade Glavenus", "Brute Wyvern", true, false, "Glavenus"),
("Gore Magala", "???", false, false, "Shagaru Magala, Chaotic Gore Magala"),
("Chaotic Gore Magala", "???", false, false, "Shagaru Magala, Gore Magala"),
("Gravios", "Flying Wyvern", false, false, "Basarios"),
("Great Maccao", "Bird Wyvern", false, false, "Maccao"),
("Gypceros", "Bird Wyvern", false, false, NULL),
("Iodrome", "Bird Wyvern", false, false, "Ioprey"),
("Kecha Wacha", "Fanged Beast", false, false, NULL),
("Khezu", "Flying Wyvern", false, false, NULL),
("Lagiacrus", "Leviathan", false, false, NULL),
("Lagombi", "Fanged Beast", false, false, "Snowbaron Lagombi"),
("Snowbaron Lagombi", "Fanged Beast", true, false, "Lagombi"),
("Lavasioth", "Piscine Wyvern", false, false, NULL),
("Malfestio", "Bird Wyvern", false, false, "Nightcloak Malfestio"),
("Nightcloak Malfestio", "Bird Wyvern", true, false, "Malfestio"),
("Mizutsune", "Leviathan", false, false, "Soulseer Mizutsune"),
("Soulseer Mizutsune", "Leviathan", true, false, "Mizutsune"),
("Najarala", "Snake Wyvern", false, false, NULL),
("Nargacuga", "Flying Wyvern", false, false, "Silverwind Nargacuga"),
("Silverwind Nargacuga", "Flying Wyvern", true, false, "Nargacuga"),
("Nerscylla", "Temnoceran", false, false, NULL),
("Nibelsnarf", "Leviathan", false, false, NULL),
("Plesioth", "Piscine Wyvern", false, false, NULL),
("Rajang", "Fanged Beast", false, false, "Furious Rajang"),
("Furious Rajang", "Fanged Beast", false, false, "Rajang"),
("Rathalos", "Flying Wyvern", false, false, "Silver Rathalos, Dreadking Rathalos, Rathian, Gold Rathian, Dreadqueen Rathian"),
("Dreadking Rathalos", "Flying Wyvern", true, false, "Rathalos, Silver Rathalos, Rathian, Gold Rathian, Dreadqueen Rathian"),
("Silver Rathalos", "Flying Wyvern", false, false, "Rathalos, Dreadqueen Rathalos, Rathian, Gold Rathian, Dreadqueen Rathian"),
("Rathian", "Flying Wyvern", false, false, "Gold Rathian, Dreadqueen Rathian, Rathalos, Silver Rathalos, Dreadking Rathalos"),
("Dreadqueen Rathian", "Flying Wyvern", true, false, "Rathian, Gold Rathian, Rathalos, Silver Rathalos, Dreadking Rathalos"),
("Gold Rathian", "Flying Wyvern", false, false, "Rathian, Dreadqueen Rathian, Rathalos, Silver Rathalos, Dreadking Rathalos"),
("Royal Ludroth", "Leviathan", false, false, "Ludroth"),
("Seltas", "Neopteron", false, false, "Seltas Queen"),
("Seltas Queen", "Neopteron", false, false, "Seltas"),
("Seregios", "Flying Wyvern", false, false, NULL),
("Shogun Ceanataur", "Carapaceon", false, false, "Ceanataur, Rustrazor Ceanataur"),
("Rustrazor Ceanataur", "Carapaceon", true, false, "Ceanataur, Shogun Ceanataur"),
("Tetuscabra", "Amphibian", false, false, "Drilltusk Tetsucabra"),
("Drilltusk Tetsucabra", "Amphibian", true, false, "Tetuscabra"),
("Tigrex", "Flying Wyvern", false, false, "Grimclaw Tigrex"),
("Grimclaw Tigrex", "Flying Wyvern", true, false, "Tigrex"),
("Ukanlos", "Flying Wyvern", false, false, "Akantor"),
("Uragaan", "Brute Wyvern", false, false, "Crystalbeard Uragaan"),
("Crystalbeard Uragaan", "Brute Wyvern", true, false, "Uragaan"),
("Velocidrome", "Bird Wyvern", false, false, "Velociprey"),
("Volvidon", "Fanged Beast", false, false, NULL),
("Yian Garuga", "Bird Wyvern", false, false, "Deadeye Yian Garuga"),
("Deadeye Yian Garuga", "Bird Wyvern", true, false, "Yian Garuga"),
("Yian Kut-ku", "Bird Wyvern", false, false, NULL),
("Zamtrios", "Amphibian", false, false, "Zamite"),
("Zinogre", "Fanged Wyvern", false, false, "Thunderlord Zinogre"),
("Thunderlord Zinogre", "Fanged Wyvern", true, false, "Zinogre"),
("Alatreon", "Elder Dragon", false, false, NULL),
("Amatsu", "Elder Dragon", false, false, NULL),
("Chameleos", "Elder Dragon", false, false, NULL),
("Fatalis", "Elder Dragon", false, false, "White Fatalis, Crimson Fatalis"),
("Crimson Fatalis", "Elder Dragon", false, false, "Fatalis, White Fatalis"),
("White Fatalis", "Elder Dragon", false, false, "Fatalis, Crimson Fatalis"),
("Kirin", "Elder Dragon", false, false, NULL),
("Kushala Daora", "Elder Dragon", false, false, NULL),
("Lao-Shan Lung", "Elder Dragon", false, false, NULL),
("Nakarkos", "Elder Dragon", false, false, NULL),
("Shagaru Magala", "Elder Dragon", false, false, "Gore Magala, Chaotic Gore Magala"),
("Teostra", "Elder Dragon", false, false, NULL),
("Valstrax", "Elder Dragon", false, false, NULL)